### ISSUE TITLE
License

### ISSUE THREAD

**Issue by guero235** [uwiger/parse_trans#17]
Is this covered by the EPL?  Thanks for the great work!  Using this in exometer :)

**Comment by uwiger** [comment]
It's EPL for now, but after consultation with Ericsson, I plan to switch to Apache 2.0. I just haven't gotten around to it yet.

**Comment by lemenkov** [comment]
Hey @uwiger!
It seems that the contents of the headers (see include directory) is still have EPL ver. 1.1 headers. Could you please consider relicensing them to Apache 2.0 as well?

**Comment by uwiger** [comment]
Will do when I find the time. If you want, you can speed up the process with a PR. ;-)

**Comment by lemenkov** [comment]
@uwiger thank you!
