### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [uwiger/parse_trans#47]
Hi, @uwiger.

Any chance you could cut a release (and Hex publish) from `master`?

I'm especially interested in:
* #41
* #42
* #43 

Thanks much.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by paulo-ferraz-oliveira** [comment]
Bump.

**Comment by uwiger** [comment]
Version 3.4.0 pushed to hex.pm

**Comment by paulo-ferraz-oliveira** [comment]
Thanks much.
